### ISSUE TITLE
[auth] Fetching UserInfo fails

### ISSUE THREAD

**Issue by danielweber90** [emdgroup/react-lib#8]
The userInfo query is failing with the error message `Failed to execute 'fetch' on 'Window': Request with GET/HEAD method cannot have[body.` This issue is causing an infinite login loop. The error is occurring in line 337 of  [/packages/auth/src/index.tsx](https://github.com/emdgroup/react-lib/blob/main/packages/auth/src/index.tsx#L337), where an empty string is being passed as the body to the useCachedQuery hook.

**Comment by monken** [comment]
@emdgroup/react-auth@1.5.3 released
